export const settings = {
  speed: 500,
  slidesToShow: 1,
  infinte: true,
  arrows: false,
  autoplay: true,
  autoplaySpeed: 1600,
  className: 'center',
  centerPadding: '30px',
  daptiveHeight: true,
  fade: true,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        speed: 500,
        slidesToShow: 1,
        infinte: true,
        arrows: false,
        autoplay: true,
        autoplaySpeed: 1600,
        className: 'center',
        daptiveHeight: true,
      },
    },
    {
      breakpoint: 600,
      settings: {
        speed: 500,
        slidesToShow: 1,
        infinte: true,
        arrows: false,
        autoplay: true,
        autoplaySpeed: 1600,
        className: 'center',
        daptiveHeight: true,
      },
    },
    {
      breakpoint: 480,
      settings: {
        speed: 500,
        slidesToShow: 1,
        infinte: true,
        arrows: false,
        autoplay: true,
        autoplaySpeed: 1600,
        className: 'center',
        daptiveHeight: true,
      },
    },
  ],
};
